### ISSUE TITLE
0.10.0 fails when input text contains a word which is only non-alphanumerical (" % ")

### ISSUE THREAD

**Issue by FredHaa** [alvenirai/punctfix#17]
Since the last update punctfix no longer handles % in the input string. I get the following exception:

```
<class 'Exception'> Something went wrong while matching word list ... Tried matching the word: der with 
Traceback (most recent call last):
  File "/home/frederik/audio/speech_recognition/src/speech_recognition/text_formater.py", line 88, in punctuate
    tokens = self.punctuation.punctuate(' '.join(stripped_tokens)).split(' ')
  File "/home/frederik/.local/lib/python3.10/site-packages/punctfix/inference.py", line 195, in punctuate
    word_prediction_list = self.populate_word_prediction_with_labels(chunks, word_prediction_list)
  File "/home/frederik/.local/lib/python3.10/site-packages/punctfix/inference.py", line 139, in populate_word_prediction_with_labels
    assert word_prediction_list[current_index].word == word, \
AssertionError: Something went wrong while matching word list ... Tried matching the word: der with 
```

For this input string:
```
overordnet set så har vi 22 % der rapporterer en eller anden form for enten brunstigst opmærksomhed eller kønskrænkende adfærd eller tvang
```

This worked completely fine in 0.9.0

**Comment by FredHaa** [comment]
Temporarily fixed by calling:
```
punctuation = PunctFixer()
punctuation.punctuate(string.replace('%', 'procent')).replace('procent', '%')
```

**Comment by sorenmulli** [comment]
Hi @FredHaa, thank you for filing an issue and giving a nice example; I'll look at it ASAP.

 I was not aware that it previously even worked with input string containing %, as the model has been trained with completely cleaned input text and the previous version had inconsistent behaviour depending on the non-alphanumerical characters. 

The desired default behaviour would be for the puncfixer to remove the `%` but this apparently fails; I'll fix soon. The alternative behaviour, to keep the `%` like in the previous version can be enabled by instantiating the model with 
```py
>>> fixer = PunctFixer(skip_normalization=True)
```
which makes your example work on version 0.10:
```py
>>> fixer.punctuate(example_text)
"Overordnet set, så har vi 22 %, der rapporterer en eller anden form for enten brunstigst, opmærksomhed eller kønskrænkende adfærd eller tvang."
```
